spring.application.name=exam-prepation
#postgres database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/statisticaustria
spring.datasource.username=postgres
spring.datasource.password=garfield26
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=exam
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


